# Generated by Django 3.1.5 on 2022-05-24 12:23

from django.db import migrations, models
from digio.utils import CreateView
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
