# Generated by Django 3.1.5 on 2022-05-31 17:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('digio', '0003_auto_20220531_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evaluation', models.IntegerField(default=99)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=70)),
                ('summary', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.AddField(
            model_name='projectngrant',
            name='is_evaluated',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='researcher',
            name='works_at',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='digio.organization'),
        ),
        migrations.DeleteModel(
            name='WorksAt',
        ),
        migrations.AddField(
            model_name='delivery',
            name='project_and_grant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digio.projectngrant'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='resercher_who_evaluates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digio.researcher'),
        ),
    ]
