# Generated by Django 3.1.5 on 2022-05-31 19:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('digio', '0004_auto_20220531_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectngrant',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2032, 1, 16, 11, 27, 29, 510162, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projectngrant',
            name='grant',
            field=models.IntegerField(default='10000'),
        ),
        migrations.AlterField(
            model_name='projectngrant',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 31, 19, 27, 29, 510083, tzinfo=utc)),
        ),
    ]
