# Generated by Django 3.1.5 on 2022-06-01 22:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('digio', '0005_auto_20220531_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='abbreviation',
            field=models.CharField(default='alefs', max_length=10),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(default='call22', max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.CharField(default='Athens', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default='alefs', max_length=30),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phones',
            field=models.CharField(default='6973975753', max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='self_street',
            field=models.CharField(default='12', max_length=30),
        ),
        migrations.AlterField(
            model_name='organization',
            name='zip_code',
            field=models.CharField(default='15774', max_length=7),
        ),
        migrations.AlterField(
            model_name='projectngrant',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2032, 1, 17, 14, 3, 13, 148507, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projectngrant',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 1, 22, 3, 13, 148467, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projectngrant',
            name='summary',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='projectngrant',
            name='tags',
            field=models.ManyToManyField(blank=True, to='digio.Tag'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='works_at',
            field=models.ForeignKey(default=uuid.UUID('13b968f2-22e2-499b-9fe0-81c5cd87e31e'), on_delete=django.db.models.deletion.CASCADE, to='digio.organization'),
        ),
    ]
