# Generated by Django 3.1.5 on 2022-06-04 21:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('digio', '0007_auto_20220601_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectngrant',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2032, 1, 20, 13, 44, 14, 473990, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projectngrant',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 4, 21, 44, 14, 473906, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='project',
        ),
        migrations.AddField(
            model_name='researcher',
            name='project',
            field=models.ManyToManyField(to='digio.ProjectnGrant'),
        ),
    ]
