# Generated by Django 3.1.5 on 2022-06-05 14:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('digio', '0011_auto_20220605_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectngrant',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2032, 1, 21, 6, 26, 9, 991478, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='projectngrant',
            name='start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 5, 14, 26, 9, 991395, tzinfo=utc)),
        ),
    ]
